from pydantic import BaseModel, Field
from typing import List, Optional, Any

class TableCellSchema(BaseModel):
    row: int = Field(..., description="Row index of the cell (0-indexed)")
    col: int = Field(..., description="Column index of the cell (0-indexed)")
    content: str = Field(..., description="Text content inside the cell")
    bbox: Optional[List[int]] = Field(None, description="Bounding box [x1, y1, x2, y2]")

class TableStructureResult(BaseModel):
    table_index: int = Field(..., description="Index of the detected table in the image")
    bbox: Optional[List[Any]] = Field(None, description="Bounding box coordinates of the table or cells")
    html: str = Field(..., description="Raw HTML string structure generated by PP-Structure")
    matrix: List[List[str]] = Field(default_factory=list, description="Parsed 2D matrix representing table rows and columns")
    csv_content: Optional[str] = Field(None, description="Extracted table formatted as CSV string")
    cell_count: int = Field(0, description="Total number of cell items in the table")



class OCRExtractionResponse(BaseModel):
    success: bool = Field(True, description="Indicates if extraction succeeded")
    tables: List[TableStructureResult] = Field(default_factory=list, description="List of tables detected in the document")
    text_blocks: List[Any] = Field(default_factory=list, description="Other text or layout elements detected")
    processing_time_ms: float = Field(0.0, description="Processing duration in milliseconds")
    message: Optional[str] = Field(None, description="Detailed info or error message if any")
