"""Add agent_configs and intent_configs

Revision ID: bdf0fbc80673
Revises: e324c12bc635
Create Date: 2026-08-20 21:40:45.955379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdf0fbc80673'
down_revision: Union[str, Sequence[str], None] = 'e324c12bc635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('few_shot_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Array of objects: [{'user': '...', 'assistant': '...'}]"),
    sa.Column('model_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('context_strategy', sa.String(length=50), nullable=True, comment="Strategy name for AIContextBuilder (e.g., 'academic', 'general')"),
    sa.Column('max_history_messages', sa.Integer(), nullable=False),
    sa.Column('allowed_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of allowed tool names'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_configs_agent_type'), 'agent_configs', ['agent_type'], unique=True)
    op.create_table('intent_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False, comment='Must match AgentConfig.agent_type'),
    sa.Column('example_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of example phrases for the intent router'),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_configs_agent_type'), 'intent_configs', ['agent_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intent_configs_agent_type'), table_name='intent_configs')
    op.drop_table('intent_configs')
    op.drop_index(op.f('ix_agent_configs_agent_type'), table_name='agent_configs')
    op.drop_table('agent_configs')
    # ### end Alembic commands ###
