"""Drop agent configs

Revision ID: c81f3d4c1446
Revises: bdf0fbc80673
Create Date: 2026-08-23 13:41:13.794149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c81f3d4c1446'
down_revision: Union[str, Sequence[str], None] = 'bdf0fbc80673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intent_configs_agent_type'), table_name='intent_configs')
    op.drop_table('intent_configs')
    op.drop_index(op.f('ix_agent_configs_agent_type'), table_name='agent_configs')
    op.drop_table('agent_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('few_shot_examples', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment="Array of objects: [{'user': '...', 'assistant': '...'}]"),
    sa.Column('model_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('context_strategy', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment="Strategy name for AIContextBuilder (e.g., 'academic', 'general')"),
    sa.Column('max_history_messages', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allowed_tools', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Array of allowed tool names'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_configs_pkey'))
    )
    op.create_index(op.f('ix_agent_configs_agent_type'), 'agent_configs', ['agent_type'], unique=True)
    op.create_table('intent_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Must match AgentConfig.agent_type'),
    sa.Column('example_phrases', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Array of example phrases for the intent router'),
    sa.Column('threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('intent_configs_pkey'))
    )
    op.create_index(op.f('ix_intent_configs_agent_type'), 'intent_configs', ['agent_type'], unique=True)
    # ### end Alembic commands ###
